language: shell
before_install:
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
script:
  - ./scripts/package.sh ${PUBLISH_DIR}
  - ./scripts/publish.sh ${PUBLISH_BRANCH} ${PUBLISH_DIR} ${REPO_URL}
git:
  depth: false
env:
  global:
    - PUBLISH_BRANCH=gh-pages
    - PUBLISH_DIR=publish
    - REPO_URL=https://seansund.github.io/kafka-connector-charts/
branches:
  - master
