apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "rmq-connector.fullname" . }}
  labels:
    app: {{ template "rmq-connector.name" . }}
    chart: {{ template "rmq-connector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "rmq-connector.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "rmq-connector.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.ports.name }}
              containerPort: {{ .Values.ports.port }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Values.volumeMounts.name }}
              mountPath: {{ .Values.volumeMounts.mountPath }}
              subPath: {{ .Values.volumeMounts.subPath }}
              readOnly: true
            - name: connector-config
              mountPath: /opt/kafka/config/connect-distributed.properties
              subPath: connect-distributed.properties
              readOnly: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      volumes:
        - name: connector-config
          configMap:
            name: connector-config
        - name: {{ .Values.volumeMounts.name }}
          secret:
            secretName: {{ .Values.volumes.secretName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600