apiVersion: v1
kind: Service
metadata:
  name: {{ template "rmq-connector.fullname" . }}
  namespace: {{ .Values.service.metadata.namespace }}
  labels:
    app: {{ template "rmq-connector.name" . }}
    chart: {{ template "rmq-connector.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "rmq-connector.name" . }}
    release: {{ .Release.Name }}
